version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: quantix
      POSTGRES_USER: david
      POSTGRES_PASSWORD: david1035
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5055:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    depends_on:
      - postgres

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: quantix
      MYSQL_USER: root
      MYSQL_PASSWORD: david12345
      MYSQL_ROOT_PASSWORD: david12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: david12345
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  postgres_data:
  pgadmin_data:
