version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: quantix
      POSTGRES_USER: david
      POSTGRES_PASSWORD: david12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5055:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
